#!/usr/bin/env bash
# HiveOS custom-miner config renderer for csd-pool-miner (P4 §1).
#
# HiveOS calls this before h-run.sh to turn the flightsheet fields into the
# miner's config + run flags. The flightsheet exposes these variables (HiveOS
# substitutes %WAL% etc. into them before sourcing the manifest):
#   $CUSTOM_TEMPLATE      the "wallet and worker template" box -> our addr20
#   $CUSTOM_USER_CONFIG   the free-form "extra config arguments" box
#                                                               -> appended verbatim
# The flightsheet "pool URL" box ($CUSTOM_URL) is intentionally ignored: the
# pool endpoint is compiled into the binary and cannot be repointed.
# We emit two files that h-run.sh consumes:
#   $CUSTOM_CONFIG_FILENAME   a TOML config holding the address
#   <config dir>/extra-flags  the extra CLI flags, one shell-word per token
#
# POSIX-sh + shellcheck-clean.

cd "$(dirname "$0")" || exit 1
# shellcheck source=/dev/null
[ -e h-manifest.conf ] && . ./h-manifest.conf

CONF="${CUSTOM_CONFIG_FILENAME:-config.toml}"
CONF_DIR="$(dirname "$CONF")"
mkdir -p "$CONF_DIR"

# The flightsheet wallet/template is the addr20 payout address. Strip a 0x
# prefix and surrounding whitespace; the miner validates it strictly.
ADDR="$(printf '%s' "${CUSTOM_TEMPLATE:-}" | tr -d '[:space:]')"
ADDR="${ADDR#0x}"

# Build the TOML config. address is the only required key; the pool endpoint is
# compiled into the binary and cannot be overridden from the flightsheet.
{
  echo "# Auto-generated by HiveOS h-config.sh — do not edit by hand."
  echo "address = \"$ADDR\""
} > "$CONF"

# Extra run flags for h-run.sh: whatever the operator typed in the "extra config
# arguments" box verbatim (e.g. --backend cuda --cpu-threads 0 --gpu-id 0,1).
# The stats flags are forced in h-run.sh, not here, so they can never be
# overridden away.
EXTRA_FLAGS_FILE="$CONF_DIR/extra-flags"
{
  if [ -n "${CUSTOM_USER_CONFIG:-}" ]; then
    printf '%s' "$CUSTOM_USER_CONFIG"
  fi
  printf '\n'
} > "$EXTRA_FLAGS_FILE"

echo "h-config: wrote $CONF (address=${ADDR:-<empty>}) and $EXTRA_FLAGS_FILE"
