#!/usr/bin/env bash
# HiveOS custom-miner config renderer for csd-pool-miner (P4 §1).
#
# HiveOS calls this before h-run.sh to turn the flightsheet fields into the
# miner's config + run flags. The flightsheet exposes these variables (HiveOS
# substitutes %WAL% etc. into them before sourcing the manifest):
#   $CUSTOM_TEMPLATE      the "wallet and worker template" box -> our addr20
#   $CUSTOM_URL           the pool URL box (host:port)          -> --pool
#   $CUSTOM_USER_CONFIG   the free-form "extra config arguments" box
#                                                               -> appended verbatim
# We emit two files that h-run.sh consumes:
#   $CUSTOM_CONFIG_FILENAME   a TOML config holding the address (+ pool if set)
#   <config dir>/extra-flags  the extra CLI flags, one shell-word per token
#
# POSIX-sh + shellcheck-clean.

cd "$(dirname "$0")" || exit 1
# shellcheck source=/dev/null
[ -e h-manifest.conf ] && . ./h-manifest.conf

CONF="${CUSTOM_CONFIG_FILENAME:-config.toml}"
CONF_DIR="$(dirname "$CONF")"
mkdir -p "$CONF_DIR"

# The flightsheet wallet/template is the addr20 payout address. Strip a 0x
# prefix and surrounding whitespace; the miner validates it strictly.
ADDR="$(printf '%s' "${CUSTOM_TEMPLATE:-}" | tr -d '[:space:]')"
ADDR="${ADDR#0x}"

# Build the TOML config. address is the only required key; the miner uses the
# compiled-in pool by default, so --pool is only emitted when the flightsheet
# URL box is set.
{
  echo "# Auto-generated by HiveOS h-config.sh — do not edit by hand."
  echo "address = \"$ADDR\""
} > "$CONF"

# Extra run flags for h-run.sh. --pool from the URL box (if any), then whatever
# the operator typed in the "extra config arguments" box verbatim (e.g.
# --backend cuda --cpu-threads 0 --gpu-id 0,1). The stats flags are forced in
# h-run.sh, not here, so they can never be overridden away.
EXTRA_FLAGS_FILE="$CONF_DIR/extra-flags"
{
  if [ -n "${CUSTOM_URL:-}" ]; then
    printf -- '--pool %s ' "$CUSTOM_URL"
  fi
  if [ -n "${CUSTOM_USER_CONFIG:-}" ]; then
    printf '%s' "$CUSTOM_USER_CONFIG"
  fi
  printf '\n'
} > "$EXTRA_FLAGS_FILE"

echo "h-config: wrote $CONF (address=${ADDR:-<empty>}) and $EXTRA_FLAGS_FILE"
