#!/usr/bin/env bash
# HiveOS custom-miner config renderer for csd-pool-miner (P4 §1).
#
# HiveOS calls this before h-run.sh to turn the flightsheet fields into the
# miner's config + run flags. The flightsheet exposes these variables (HiveOS
# substitutes %WAL% etc. into them before sourcing the manifest):
#   $CUSTOM_TEMPLATE      the "wallet and worker template" box -> our addr20
#   $CUSTOM_USER_CONFIG   the free-form "extra config arguments" box
#                                                               -> appended verbatim
# The flightsheet "pool URL" box ($CUSTOM_URL) is intentionally ignored: the
# pool endpoint is compiled into the binary and cannot be repointed.
# We emit two files that h-run.sh consumes:
#   $CUSTOM_CONFIG_FILENAME   a TOML config holding the address
#   <config dir>/extra-flags  the extra CLI flags, one shell-word per token
#
# POSIX-sh + shellcheck-clean.

cd "$(dirname "$0")" || exit 1
# shellcheck source=/dev/null
[ -e h-manifest.conf ] && . ./h-manifest.conf

CONF="${CUSTOM_CONFIG_FILENAME:-config.toml}"
CONF_DIR="$(dirname "$CONF")"
mkdir -p "$CONF_DIR"

# The flightsheet "wallet and worker template" is the addr20 payout address. Put
# the LITERAL CSD address here, NOT %WAL% — CSD is not a HiveOS-known coin, so the
# %WAL% macro is never expanded and would leave the address empty. An optional
# ".worker" suffix (HiveOS appends %WORKER_NAME%) is dropped. Strip whitespace +
# a 0x prefix; the miner validates the result strictly (40 hex, or 42 with 0x).
ADDR="$(printf '%s' "${CUSTOM_TEMPLATE:-}" | tr -d '[:space:]')"
ADDR="${ADDR%%.*}"   # drop a ".worker" suffix, if any
ADDR="${ADDR#0x}"    # drop a 0x prefix, if any
# If any HiveOS macro (%WAL%, %WORKER_NAME%, …) was left UNEXPANDED, blank it so
# the miner emits its clear "address must be 40 hex chars" error rather than
# trying to mine to a literal "%WAL%".
case "$ADDR" in *%*) ADDR="" ;; esac

# Build the TOML config. address is the only required key; the pool endpoint is
# compiled into the binary and cannot be overridden from the flightsheet.
{
  echo "# Auto-generated by HiveOS h-config.sh — do not edit by hand."
  echo "address = \"$ADDR\""
} > "$CONF"

# Extra run flags for h-run.sh: whatever the operator typed in the "extra config
# arguments" box verbatim (e.g. --backend cuda --cpu-threads 0 --gpu-id 0,1).
# The stats flags are forced in h-run.sh, not here, so they can never be
# overridden away.
EXTRA_FLAGS_FILE="$CONF_DIR/extra-flags"
{
  if [ -n "${CUSTOM_USER_CONFIG:-}" ]; then
    printf '%s' "$CUSTOM_USER_CONFIG"
  fi
  printf '\n'
} > "$EXTRA_FLAGS_FILE"

if [ -z "$ADDR" ]; then
  echo "h-config: WARNING — empty address. Put your CSD addr20 (40-hex) DIRECTLY in the 'Wallet and worker template' field, NOT %WAL%. The miner will refuse to start until this is set."
else
  echo "h-config: wrote $CONF (address=$ADDR) and $EXTRA_FLAGS_FILE"
fi
